# Generated by Django 3.0.3 on 2020-03-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200305_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_url',
            field=models.CharField(max_length=300),
        ),
    ]
