# Generated by Django 3.0.3 on 2020-03-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_static_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
