# Generated by Django 3.0.3 on 2020-04-19 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mails',
            name='content',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='mails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mails',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mails',
            name='document',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
